// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: Courses.proto

//protoc --proto_path=src/protos --micro_out=. --go_out=. Courses.proto
//设置go_package为"src/Courses"，执行上命令成功在go_out位置创建了2个文件
//import "Common.proto";

package Courses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CourseService service

func NewCourseServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CourseService service

type CourseService interface {
	ListForTop(ctx context.Context, in *CourseLstRequest, opts ...client.CallOption) (*CourseLstResponse, error)
	GetDetail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error)
}

type courseService struct {
	c    client.Client
	name string
}

func NewCourseService(name string, c client.Client) CourseService {
	return &courseService{
		c:    c,
		name: name,
	}
}

func (c *courseService) ListForTop(ctx context.Context, in *CourseLstRequest, opts ...client.CallOption) (*CourseLstResponse, error) {
	req := c.c.NewRequest(c.name, "CourseService.ListForTop", in)
	out := new(CourseLstResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseService) GetDetail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error) {
	req := c.c.NewRequest(c.name, "CourseService.GetDetail", in)
	out := new(DetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CourseService service

type CourseServiceHandler interface {
	ListForTop(context.Context, *CourseLstRequest, *CourseLstResponse) error
	GetDetail(context.Context, *DetailRequest, *DetailResponse) error
}

func RegisterCourseServiceHandler(s server.Server, hdlr CourseServiceHandler, opts ...server.HandlerOption) error {
	type courseService interface {
		ListForTop(ctx context.Context, in *CourseLstRequest, out *CourseLstResponse) error
		GetDetail(ctx context.Context, in *DetailRequest, out *DetailResponse) error
	}
	type CourseService struct {
		courseService
	}
	h := &courseServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CourseService{h}, opts...))
}

type courseServiceHandler struct {
	CourseServiceHandler
}

func (h *courseServiceHandler) ListForTop(ctx context.Context, in *CourseLstRequest, out *CourseLstResponse) error {
	return h.CourseServiceHandler.ListForTop(ctx, in, out)
}

func (h *courseServiceHandler) GetDetail(ctx context.Context, in *DetailRequest, out *DetailResponse) error {
	return h.CourseServiceHandler.GetDetail(ctx, in, out)
}
